version: '3'
services:
  dhis2-dwh:
    build:
      context: .
      dockerfile: Dockerfile
    image: dhis2-dwh
    container_name: dhis2-dwh
    restart: unless-stopped
    env_file: .env
    environment:
      - API_KEY=${API_KEY}
      - API_PORT=${API_PORT}
      - DATABASE_DIALECT=${DATABASE_DIALECT}
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_PORT=${DATABASE_PORT}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DHIS2_API_BASE_URL=${DHIS2_API_BASE_URL}
      - DHIS2_USERNAME=${DHIS2_USERNAME}
      - DHIS2_PASSWORD=${DHIS2_PASSWORD}
    ports:
      - "${API_PORT}:${API_PORT}"